<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="links"
    nsURI="http://eclipse.org/graphiti/links" nsPrefix="li">
  <eClassifiers xsi:type="ecore:EClass" name="PictogramLink" eSuperTypes="pictograms.ecore#//PropertyContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramElement" ordered="false"
        unique="false" eType="ecore:EClass pictograms.ecore#//PictogramElement" eOpposite="pictograms.ecore#//PictogramElement/link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramLink" ordered="false"
        unique="false" lowerBound="1" eType="#//DiagramLink" eOpposite="#//DiagramLink/pictogramLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessObjects" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" ordered="false"
        unique="false" eType="ecore:EClass pictograms.ecore#//Diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramLinks" ordered="false"
        upperBound="-1" eType="#//PictogramLink" eOpposite="#//PictogramLink/diagramLink"/>
  </eClassifiers>
</ecore:EPackage>
