<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pictograms"
    nsURI="http://eclipse.org/graphiti/pictograms" nsPrefix="pi">
  <eClassifiers xsi:type="ecore:EClass" name="Shape" eSuperTypes="#//AnchorContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" ordered="false"
        unique="false" eType="#//ContainerShape" eOpposite="#//ContainerShape/children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerShape" eSuperTypes="#//Shape">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Shape" containment="true" eOpposite="#//Shape/container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//ContainerShape #//StyleContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gridUnit" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramTypeId" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" ordered="false"
        upperBound="-1" eType="#//Connection" containment="true" eOpposite="#//Connection/parent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="snapToGrid" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showGuides" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colors" ordered="false"
        upperBound="-1" eType="ecore:EClass datatypes.ecore#//Color" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramLinks" ordered="false"
        upperBound="-1" eType="ecore:EClass links.ecore#//PictogramLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphicsAlgorithm" abstract="true" eSuperTypes="#//GraphicsAlgorithmContainer #//AbstractStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphicsAlgorithmChildren"
        upperBound="-1" eType="#//GraphicsAlgorithm" containment="true" eOpposite="#//GraphicsAlgorithm/parentGraphicsAlgorithm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentGraphicsAlgorithm"
        ordered="false" unique="false" eType="#//GraphicsAlgorithm" eOpposite="#//GraphicsAlgorithm/graphicsAlgorithmChildren"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramElement" ordered="false"
        unique="false" eType="#//PictogramElement" eOpposite="#//PictogramElement/graphicsAlgorithm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" ordered="false"
        unique="false" eType="#//Style"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polyline" eSuperTypes="#//GraphicsAlgorithm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1"
        eType="ecore:EClass datatypes.ecore#//Point" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ellipse" eSuperTypes="#//GraphicsAlgorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="PictogramElement" abstract="true" eSuperTypes="#//GraphicsAlgorithmContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphicsAlgorithm" ordered="false"
        unique="false" eType="#//GraphicsAlgorithm" containment="true" eOpposite="#//GraphicsAlgorithm/pictogramElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" ordered="false" unique="false"
        eType="ecore:EClass links.ecore#//PictogramLink" containment="true" eOpposite="links.ecore#//PictogramLink/pictogramElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//AnchorContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" ordered="false"
        unique="false" lowerBound="1" eType="#//Anchor" eOpposite="#//Anchor/outgoingConnections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" ordered="false" unique="false"
        lowerBound="1" eType="#//Anchor" eOpposite="#//Anchor/incomingConnections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false"
        unique="false" lowerBound="1" eType="#//Diagram" eOpposite="#//Diagram/connections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionDecorators" upperBound="-1"
        eType="#//ConnectionDecorator" containment="true" eOpposite="#//ConnectionDecorator/connection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anchor" abstract="true" eSuperTypes="#//PictogramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false"
        unique="false" lowerBound="1" eType="#//AnchorContainer" eOpposite="#//AnchorContainer/anchors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections" ordered="false"
        upperBound="-1" eType="#//Connection" eOpposite="#//Connection/start"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnections" ordered="false"
        upperBound="-1" eType="#//Connection" eOpposite="#//Connection/end"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedGraphicsAlgorithm"
        ordered="false" unique="false" eType="#//GraphicsAlgorithm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnchorContainer" abstract="true" eSuperTypes="#//PictogramElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anchors" ordered="false"
        upperBound="-1" eType="#//Anchor" containment="true" eOpposite="#//Anchor/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixPointAnchor" eSuperTypes="#//Anchor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass datatypes.ecore#//Point"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoxRelativeAnchor" eSuperTypes="#//Anchor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeWidth" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeHeight" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChopboxAnchor" eSuperTypes="#//Anchor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//AbstractText"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionDecorator" eSuperTypes="#//Shape">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationRelative" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" ordered="false"
        unique="false" lowerBound="1" eType="#//Connection" eOpposite="#//Connection/connectionDecorators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FreeFormConnection" eSuperTypes="#//Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendpoints" upperBound="-1"
        eType="ecore:EClass datatypes.ecore#//Point" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManhattanConnection" eSuperTypes="#//Connection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Polygon" eSuperTypes="#//Polyline"/>
  <eClassifiers xsi:type="ecore:EEnum" name="LineStyle">
    <eLiterals name="SOLID"/>
    <eLiterals name="DASH" value="1"/>
    <eLiterals name="DASHDOT" value="2"/>
    <eLiterals name="DASHDOTDOT" value="3"/>
    <eLiterals name="DOT" value="4"/>
    <eLiterals name="UNSPECIFIED" value="5" literal="UNSPECIFIED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Orientation">
    <eLiterals name="ALIGNMENT_CENTER"/>
    <eLiterals name="ALIGNMENT_LEFT" value="1"/>
    <eLiterals name="ALIGNMENT_TOP" value="2"/>
    <eLiterals name="ALIGNMENT_RIGHT" value="3"/>
    <eLiterals name="ALIGNMENT_BOTTOM" value="4"/>
    <eLiterals name="ALIGNMENT_MIDDLE" value="5"/>
    <eLiterals name="UNSPECIFIED" value="6" literal="UNSPECIFIED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangle" eSuperTypes="#//GraphicsAlgorithm"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoundedRectangle" eSuperTypes="#//GraphicsAlgorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerHeight" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerWidth" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Font">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italic" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenderingStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefinedStyleId" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//GraphicsAlgorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stretchH" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stretchV" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proportional" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatformGraphicsAlgorithm" eSuperTypes="#//GraphicsAlgorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphicsAlgorithmContainer" abstract="true"
      eSuperTypes="#//PropertyContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractText" abstract="true" eSuperTypes="#//GraphicsAlgorithm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="font" ordered="false" unique="false"
        eType="#//Font" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontalAlignment" ordered="false"
        unique="false" eType="#//Orientation" defaultValueLiteral="ALIGNMENT_LEFT"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verticalAlignment" ordered="false"
        unique="false" eType="#//Orientation" defaultValueLiteral="ALIGNMENT_CENTER"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiText" eSuperTypes="#//AbstractText"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" ordered="false"
        upperBound="-1" eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StyleContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="styles" ordered="false"
        upperBound="-1" eType="#//Style" containment="true" eOpposite="#//Style/styleContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Style" eSuperTypes="#//StyleContainer #//AbstractStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="font" ordered="false" unique="false"
        eType="#//Font" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontalAlignment" ordered="false"
        unique="false" eType="#//Orientation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verticalAlignment" ordered="false"
        unique="false" eType="#//Orientation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stretchH" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stretchV" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proportional" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="styleContainer" ordered="false"
        unique="false" lowerBound="1" eType="#//StyleContainer" eOpposite="#//StyleContainer/styles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStyle" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" ordered="false"
        unique="false" eType="ecore:EClass datatypes.ecore#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreground" ordered="false"
        unique="false" eType="ecore:EClass datatypes.ecore#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineWidth" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineStyle" ordered="false"
        unique="false" eType="#//LineStyle" defaultValueLiteral="SOLID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filled" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineVisible" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="renderingStyle" ordered="false"
        unique="false" eType="#//RenderingStyle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transparency" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        defaultValueLiteral="0"/>
  </eClassifiers>
</ecore:EPackage>
